"""
tests/conftest.py
─────────────────
Shared pytest fixtures for the Job Seeker's Concierge test suite.

All fixtures use mocks — no real Firebase or Gemini API calls are made.

Fixtures:
  client              — AsyncClient pointed at the FastAPI app.
  mock_firebase_token — Patches firebase_admin.auth.verify_id_token to
                        return a fake decoded token without hitting Firebase.
  sample_resume_txt   — bytes of a minimal plain-text resume.
  sample_resume_pdf   — bytes of a minimal in-memory PDF generated by PyPDF2.
"""

import io
import os

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient

# ── Set stub env vars before any app module is imported ──────────────────────
# These prevent pydantic_settings from raising a validation error when Settings
# is instantiated during import of the FastAPI app.
os.environ.setdefault("GEMINI_API_KEY", "test-gemini-key-placeholder")
os.environ.setdefault(
    "FIREBASE_SERVICE_ACCOUNT_JSON",
    '{"type":"service_account","project_id":"test","private_key_id":"k",'
    '"private_key":"-----BEGIN RSA PRIVATE KEY-----\\nMIIEowIBAAKCAQEA2a\\n'
    "-----END RSA PRIVATE KEY-----\\n\","
    '"client_email":"test@test.iam.gserviceaccount.com","client_id":"1",'
    '"auth_uri":"https://accounts.google.com/o/oauth2/auth",'
    '"token_uri":"https://oauth2.googleapis.com/token"}',
)
os.environ.setdefault("LOG_LEVEL", "WARNING")  # Suppress logs during tests

from main import app  # noqa: E402  (must come after env var setup)

# ── Fake decoded Firebase token ───────────────────────────────────────────────
FAKE_UID = "test-user-uid-abc123"
FAKE_DECODED_TOKEN: dict = {
    "uid": FAKE_UID,
    "email": "test@example.com",
    "email_verified": True,
}


@pytest_asyncio.fixture
async def client():
    """
    AsyncClient pointed at the FastAPI app via ASGI transport.
    No real HTTP server is started; requests are handled in-process.
    """
    async with AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test"
    ) as ac:
        yield ac


@pytest.fixture
def mock_firebase_token(monkeypatch):
    """
    Patch firebase_admin.auth.verify_id_token to return FAKE_DECODED_TOKEN
    without contacting Firebase. Also patches firebase_admin._apps to prevent
    'app not initialized' errors.
    """
    import firebase_admin

    # Simulate an already-initialized Firebase app.
    monkeypatch.setattr(firebase_admin, "_apps", {"[DEFAULT]": object()})

    import firebase_admin.auth as fb_auth

    monkeypatch.setattr(
        fb_auth,
        "verify_id_token",
        lambda token, **kwargs: FAKE_DECODED_TOKEN,
    )
    return FAKE_DECODED_TOKEN


@pytest.fixture
def sample_resume_txt() -> bytes:
    """
    Minimal plain-text resume (well over 100 chars) for upload tests.
    """
    resume = (
        "Jane Doe\n"
        "jane.doe@example.com | linkedin.com/in/janedoe\n\n"
        "EXPERIENCE\n"
        "Software Engineer — Acme Corp (2021–Present)\n"
        "• Built REST APIs with Python and FastAPI serving 50k daily users.\n"
        "• Reduced API latency by 35% through Redis caching.\n"
        "• Led migration of 3 services to Docker on AWS ECS.\n\n"
        "Junior Developer — StartupXYZ (2019–2021)\n"
        "• Developed React front-end components.\n"
        "• Wrote pytest integration tests achieving 85% coverage.\n\n"
        "EDUCATION\n"
        "B.Sc. Computer Science — State University (2019)\n\n"
        "SKILLS\n"
        "Python, FastAPI, React, Docker, AWS, PostgreSQL, Redis, pytest\n"
    )
    return resume.encode("utf-8")


@pytest.fixture
def sample_resume_pdf(sample_resume_txt) -> bytes:
    """
    Minimal in-memory PDF built from the plain-text resume using PyPDF2.
    Returns raw PDF bytes suitable for upload tests.
    """
    import PyPDF2
    from PyPDF2 import PdfWriter

    writer = PdfWriter()
    writer.add_blank_page(width=612, height=792)

    # PyPDF2's blank page doesn't embed text we can extract, but it creates a
    # structurally valid PDF. For the 'valid PDF returns extracted string'
    # test we will mock the parser; this fixture is used to test that a real
    # PDF bytes object is accepted by the upload endpoint without a 415 error.
    buffer = io.BytesIO()
    writer.write(buffer)
    buffer.seek(0)
    return buffer.read()
